; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
test_framework = unity

[arduino]
test_filter = test_arduino_*
platform = atmelavr
framework = arduino
board = uno
lib_deps = 
	arduino-libraries/Servo@^1.3.0

[env:main]
extends = arduino
build_src_filter = +<main.cpp>

[env:getIMUdata]
extends = arduino
build_src_filter = +<getIMUdata.cpp>

[env:rcFlightTest]
extends = arduino
build_src_filter = +<rcFlightTest.cpp>

[env:native]
test_filter = test_native_*
platform = native
test_framework = unity
